version: '3'
services:
    waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            - mysql
        command: mysql:3306

    mlflow:
        build: ./mlflow
        depends_on:
            - mysql
            - waitfordb
        ports:
            - "${APP_PORT}:5000"
        env_file: .env
        command:
            - "sh"
            - "-c"
            - "poetry run mlflow server
                --backend-store-uri mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/mlflow
                --default-artifact-root s3://${S3_BUCKET}
                --host 0.0.0.0
                --port 5000"
        volumes:
            - virtualenvs:/root/.cache/pypoetry/virtualenvs
        restart: always

    mysql:
        image: mysql:8.0
        environment:
            TZ: "Asia/Tokyo"
            MYSQL_DATABASE: "mlflow"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        restart: always

volumes:
    mysql:
    virtualenvs:
