version: '3'
services:
    waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            - mysql
        command: mysql:3306

    mlflow:
        build: ./mlflow
        depends_on:
            - mysql
            - waitfordb
        ports:
            - "5000:5000"
        environment:
            DB_URI: "mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/mlflow"
            S3_BUCKET: ${S3_BUCKET}
        restart: always

    mysql:
        image: mysql:8.0
        environment:
            TZ: "Asia/Tokyo"
            MYSQL_DATABASE: "mlflow"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        restart: always

volumes:
    mysql:
