[tool.poetry]
name = "mlflow_server"
version = "0.1.0"
description = ""
authors = ["altescy <altescy@fastmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
mlflow = "^1.9.0"
mysqlclient = "^1.4.6"
boto3 = "^1.14.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
